<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>4e32aa90-959d-44cc-868d-514700de3e91</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Models\cardsSpecial.json" CopyToOutputDirectory="PreserveNewest" />
		<None Include="Models\cards.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\images\cards\" />
		<Folder Include="wwwroot\images\specialCards\" />
	</ItemGroup>

</Project>